import type { Metadata } from "next";
import ThemeRegistry from "./theme/theme-registry"
import { publicSans } from "./ui/font";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} antialised`}>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
